#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/phi/modular_phi.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_phi.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
from collections.abc import Callable
from typing import Optional

import torch
import torch.nn as nn

from ...activations import ACT2FN
from ...cache_utils import Cache, DynamicCache
from ...generation import GenerationMixin
from ...integrations import use_kernel_func_from_hub, use_kernelized_func
from ...masking_utils import create_causal_mask
from ...modeling_layers import (
    GenericForSequenceClassification,
    GenericForTokenClassification,
    GradientCheckpointingLayer,
)
from ...modeling_outputs import BaseModelOutputWithPast, CausalLMOutputWithPast
from ...modeling_rope_utils import ROPE_INIT_FUNCTIONS, dynamic_rope_update
from ...modeling_utils import ALL_ATTENTION_FUNCTIONS, PreTrainedModel
from ...processing_utils import Unpack
from ...utils import TransformersKwargs, auto_docstring
from ...utils.generic import can_return_tuple, maybe_autocast, merge_with_config_defaults
from ...utils.output_capturing import capture_outputs
from .configuration_phi import PhiConfig

import os
from huggingface_hub import snapshot_download
from safetensors.torch import load_file
from torch_mlir import fx, ir
from torch._decomp import get_decompositions
from torch_mlir.extras.fx_decomp_util import get_decomposition_table




class PhiRotaryEmbedding(nn.Module):
    inv_freq: torch.Tensor  # fix linting for `register_buffer`

    def __init__(self, config: PhiConfig, device=None):
        super().__init__()
        self.max_seq_len_cached = config.max_position_embeddings
        self.original_max_seq_len = config.max_position_embeddings

        self.config = config

        self.rope_type = self.config.rope_parameters["rope_type"]
        rope_init_fn: Callable = self.compute_default_rope_parameters
        if self.rope_type != "default":
            rope_init_fn = ROPE_INIT_FUNCTIONS[self.rope_type]
        inv_freq, self.attention_scaling = rope_init_fn(self.config, device)

        self.register_buffer("inv_freq", inv_freq, persistent=False)
        self.register_buffer("original_inv_freq", inv_freq.clone(), persistent=False)

    @staticmethod
    def compute_default_rope_parameters(
        config: PhiConfig | None = None,
        device: Optional["torch.device"] = None,
        seq_len: int | None = None,
    ) -> tuple["torch.Tensor", float]:
        """
        Computes the inverse frequencies according to the original RoPE implementation
        Args:
            config ([`~transformers.PreTrainedConfig`]):
                The model configuration.
            device (`torch.device`):
                The device to use for initialization of the inverse frequencies.
            seq_len (`int`, *optional*):
                The current sequence length. Unused for this type of RoPE.
        Returns:
            Tuple of (`torch.Tensor`, `float`), containing the inverse frequencies for the RoPE embeddings and the
            post-processing scaling factor applied to the computed cos/sin (unused in this type of RoPE).
        """
        base = config.rope_parameters["rope_theta"]
        partial_rotary_factor = config.rope_parameters.get("partial_rotary_factor", 1.0)
        head_dim = getattr(config, "head_dim", None) or config.hidden_size // config.num_attention_heads
        dim = int(head_dim * partial_rotary_factor)

        attention_factor = 1.0  # Unused in this type of RoPE

        # Compute the inverse frequencies
        inv_freq = 1.0 / (
            base ** (torch.arange(0, dim, 2, dtype=torch.int64).to(device=device, dtype=torch.float) / dim)
        )
        return inv_freq, attention_factor

    @torch.no_grad()
    @dynamic_rope_update  # power user: used with advanced RoPE types (e.g. dynamic rope)
    def forward(self, x, position_ids):
        inv_freq_expanded = self.inv_freq[None, :, None].float().expand(position_ids.shape[0], -1, 1).to(x.device)
        position_ids_expanded = position_ids[:, None, :].float()

        device_type = x.device.type if isinstance(x.device.type, str) and x.device.type != "mps" else "cpu"
        with maybe_autocast(device_type=device_type, enabled=False):  # Force float32
            freqs = (inv_freq_expanded.float() @ position_ids_expanded.float()).transpose(1, 2)
            emb = torch.cat((freqs, freqs), dim=-1)
            cos = emb.cos() * self.attention_scaling
            sin = emb.sin() * self.attention_scaling

        return cos.to(dtype=x.dtype), sin.to(dtype=x.dtype)


def rotate_half(x):
    """Rotates half the hidden dims of the input."""
    x1 = x[..., : x.shape[-1] // 2]
    x2 = x[..., x.shape[-1] // 2 :]
    return torch.cat((-x2, x1), dim=-1)


@use_kernel_func_from_hub("rotary_pos_emb")
def apply_rotary_pos_emb(q, k, cos, sin, unsqueeze_dim=1):
    """Applies Rotary Position Embedding to the query and key tensors.

    Args:
        q (`torch.Tensor`): The query tensor.
        k (`torch.Tensor`): The key tensor.
        cos (`torch.Tensor`): The cosine part of the rotary embedding.
        sin (`torch.Tensor`): The sine part of the rotary embedding.
        unsqueeze_dim (`int`, *optional*, defaults to 1):
            The 'unsqueeze_dim' argument specifies the dimension along which to unsqueeze cos[position_ids] and
            sin[position_ids] so that they can be properly broadcasted to the dimensions of q and k. For example, note
            that cos[position_ids] and sin[position_ids] have the shape [batch_size, seq_len, head_dim]. Then, if q and
            k have the shape [batch_size, heads, seq_len, head_dim], then setting unsqueeze_dim=1 makes
            cos[position_ids] and sin[position_ids] broadcastable to the shapes of q and k. Similarly, if q and k have
            the shape [batch_size, seq_len, heads, head_dim], then set unsqueeze_dim=2.
    Returns:
        `tuple(torch.Tensor)` comprising of the query and key tensors rotated using the Rotary Position Embedding.
    """
    cos = cos.unsqueeze(unsqueeze_dim)
    sin = sin.unsqueeze(unsqueeze_dim)
    q_embed = (q * cos) + (rotate_half(q) * sin)
    k_embed = (k * cos) + (rotate_half(k) * sin)
    return q_embed, k_embed


def repeat_kv(hidden_states: torch.Tensor, n_rep: int) -> torch.Tensor:
    """
    This is the equivalent of torch.repeat_interleave(x, dim=1, repeats=n_rep). The hidden states go from (batch,
    num_key_value_heads, seqlen, head_dim) to (batch, num_attention_heads, seqlen, head_dim)
    """
    batch, num_key_value_heads, slen, head_dim = hidden_states.shape
    if n_rep == 1:
        return hidden_states
    hidden_states = hidden_states[:, :, None, :, :].expand(batch, num_key_value_heads, n_rep, slen, head_dim)
    return hidden_states.reshape(batch, num_key_value_heads * n_rep, slen, head_dim)


def eager_attention_forward(
    module: nn.Module,
    query: torch.Tensor,
    key: torch.Tensor,
    value: torch.Tensor,
    attention_mask: torch.Tensor | None,
    scaling: float,
    dropout: float = 0.0,
    **kwargs: Unpack[TransformersKwargs],
):
    key_states = repeat_kv(key, module.num_key_value_groups)
    value_states = repeat_kv(value, module.num_key_value_groups)

    attn_weights = torch.matmul(query, key_states.transpose(2, 3)) * scaling
    if attention_mask is not None:
        attn_weights = attn_weights + attention_mask

    attn_weights = nn.functional.softmax(attn_weights, dim=-1, dtype=torch.float32).to(query.dtype)
    attn_weights = nn.functional.dropout(attn_weights, p=dropout, training=module.training)
    attn_output = torch.matmul(attn_weights, value_states)
    attn_output = attn_output.transpose(1, 2).contiguous()

    return attn_output, attn_weights


@use_kernelized_func(apply_rotary_pos_emb)
class PhiAttention(nn.Module):
    """Multi-headed attention from 'Attention Is All You Need' paper"""

    def __init__(self, config: PhiConfig, layer_idx: int):
        super().__init__()
        self.config = config
        self.layer_idx = layer_idx
        self.head_dim = getattr(config, "head_dim", config.hidden_size // config.num_attention_heads)
        self.num_key_value_groups = config.num_attention_heads // config.num_key_value_heads
        self.scaling = self.head_dim**-0.5
        self.attention_dropout = config.attention_dropout
        self.is_causal = True

        # remove gemv
        self.q_proj = nn.Identity() # nn.Linear(config.hidden_size, config.num_attention_heads * self.head_dim, bias=True)
        self.k_proj = nn.Identity() # nn.Linear(config.hidden_size, config.num_key_value_heads * self.head_dim, bias=True)
        self.v_proj = nn.Identity() # nn.Linear(config.hidden_size, config.num_key_value_heads * self.head_dim, bias=True)
        self.dense = nn.Identity() # nn.Linear(config.num_attention_heads * self.head_dim, config.hidden_size, bias=True)

        
        self.rotary_ndims = int(self.head_dim * config.rope_parameters["partial_rotary_factor"])
        self.qk_layernorm = config.qk_layernorm
        if self.qk_layernorm:
            self.q_layernorm = nn.LayerNorm(
                config.hidden_size // config.num_attention_heads, eps=config.layer_norm_eps, elementwise_affine=True
            )
            self.k_layernorm = nn.LayerNorm(
                config.hidden_size // config.num_attention_heads, eps=config.layer_norm_eps, elementwise_affine=True
            )

    def forward(
        self,
        hidden_states: torch.Tensor,
        position_embeddings: tuple[torch.Tensor, torch.Tensor],
        attention_mask: torch.Tensor | None,
        past_key_values: Cache | None = None,
        **kwargs,
    ) -> tuple[torch.Tensor, torch.Tensor | None]:
        input_shape = hidden_states.shape[:-1]
        hidden_shape = (*input_shape, -1, self.head_dim)

        query_states = self.q_proj(hidden_states).view(hidden_shape).transpose(1, 2)
        key_states = self.k_proj(hidden_states).view(hidden_shape).transpose(1, 2)
        value_states = self.v_proj(hidden_states).view(hidden_shape).transpose(1, 2)

        if self.qk_layernorm:
            query_states = self.q_layernorm(query_states)
            key_states = self.k_layernorm(key_states)

        cos, sin = position_embeddings
        # Partial rotary embedding
        query_rot, query_pass = (
            query_states[..., : self.rotary_ndims],
            query_states[..., self.rotary_ndims :],
        )
        key_rot, key_pass = (
            key_states[..., : self.rotary_ndims],
            key_states[..., self.rotary_ndims :],
        )
        # [batch_size, seq_length, num_heads, head_dim // config.partial_rotary_factor]
        query_rot, key_rot = apply_rotary_pos_emb(query_rot, key_rot, cos, sin)

        # [batch_size, seq_length, num_heads, head_dim]
        query_states = torch.cat((query_rot, query_pass), dim=-1)
        key_states = torch.cat((key_rot, key_pass), dim=-1)

        if past_key_values is not None:
            key_states, value_states = past_key_values.update(key_states, value_states, self.layer_idx)

        attention_interface: Callable = ALL_ATTENTION_FUNCTIONS.get_interface(
            self.config._attn_implementation, eager_attention_forward
        )

        attn_output, attn_weights = attention_interface(
            self,
            query_states,
            key_states,
            value_states,
            attention_mask,
            dropout=0.0 if not self.training else self.attention_dropout,
            scaling=self.scaling,
            **kwargs,
        )

        attn_output = attn_output.reshape(*input_shape, -1).contiguous()
        attn_output = self.dense(attn_output)
        return attn_output, attn_weights


class PhiMLP(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.config = config
        self.activation_fn = ACT2FN[config.hidden_act]
        # remove gemv 
        self.fc1 = nn.Identity()# nn.Linear(config.hidden_size, config.intermediate_size)
        self.fc2 = nn.Identity()#  nn.Linear(config.intermediate_size, config.hidden_size)

    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:
        hidden_states = self.fc1(hidden_states)
        hidden_states = self.activation_fn(hidden_states)
        hidden_states = self.fc2(hidden_states)
        return hidden_states


class PhiDecoderLayer(GradientCheckpointingLayer):
    def __init__(self, config: PhiConfig, layer_idx: int):
        super().__init__()
        self.self_attn = PhiAttention(config, layer_idx=layer_idx)
        self.mlp = PhiMLP(config)
        self.input_layernorm = nn.LayerNorm(config.hidden_size, eps=config.layer_norm_eps)
        self.resid_dropout = nn.Dropout(config.resid_pdrop)

    def forward(
        self,
        hidden_states: torch.Tensor,
        attention_mask: torch.Tensor | None = None,
        position_ids: torch.LongTensor | None = None,
        past_key_values: Cache | None = None,
        use_cache: bool | None = False,
        position_embeddings: tuple[torch.Tensor, torch.Tensor] | None = None,
        **kwargs: Unpack[TransformersKwargs],
    ) -> torch.Tensor:
        residual = hidden_states

        hidden_states = self.input_layernorm(hidden_states)

        attn_outputs, _ = self.self_attn(
            hidden_states=hidden_states,
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_values=past_key_values,
            use_cache=use_cache,
            position_embeddings=position_embeddings,
            **kwargs,
        )
        attn_outputs = self.resid_dropout(attn_outputs)

        feed_forward_hidden_states = self.resid_dropout(self.mlp(hidden_states))
        hidden_states = attn_outputs + feed_forward_hidden_states + residual

        return hidden_states


@auto_docstring
class PhiPreTrainedModel(PreTrainedModel):
    config: PhiConfig
    base_model_prefix = "model"
    supports_gradient_checkpointing = True
    _no_split_modules = ["PhiDecoderLayer"]
    _skip_keys_device_placement = ["past_key_values"]
    _supports_flash_attn = True
    _supports_sdpa = True
    _supports_flex_attn = True

    _can_compile_fullgraph = True
    _supports_attention_backend = True
    _can_record_outputs = {
        "hidden_states": PhiDecoderLayer,
        "attentions": PhiAttention,
    }


@auto_docstring
class PhiModel(PhiPreTrainedModel):
    def __init__(self, config: PhiConfig):
        super().__init__(config)
        self.padding_idx = config.pad_token_id
        self.vocab_size = config.vocab_size

        self.embed_tokens = nn.Embedding(config.vocab_size, config.hidden_size, self.padding_idx)
        self.layers = nn.ModuleList(
            [PhiDecoderLayer(config, layer_idx) for layer_idx in range(config.num_hidden_layers)]
        )
        self.rotary_emb = PhiRotaryEmbedding(config=config)
        self.gradient_checkpointing = False
        self.embed_dropout = nn.Dropout(config.embd_pdrop)
        self.final_layernorm = nn.LayerNorm(config.hidden_size, eps=config.layer_norm_eps)

        # Initialize weights and apply final processing
        self.post_init()

    @merge_with_config_defaults
    @capture_outputs
    @auto_docstring
    def forward(
        self,
        input_ids: torch.LongTensor | None = None,
        attention_mask: torch.Tensor | None = None,
        position_ids: torch.LongTensor | None = None,
        past_key_values: Cache | None = None,
        inputs_embeds: torch.FloatTensor | None = None,
        use_cache: bool | None = None,
        **kwargs: Unpack[TransformersKwargs],
    ) -> BaseModelOutputWithPast:
        if (input_ids is None) ^ (inputs_embeds is not None):
            raise ValueError("You must specify exactly one of input_ids or inputs_embeds")

        if inputs_embeds is None:
            inputs_embeds = self.embed_tokens(input_ids)

        if use_cache and past_key_values is None:
            past_key_values = DynamicCache(config=self.config)

        if position_ids is None:
            past_seen_tokens = past_key_values.get_seq_length() if past_key_values is not None else 0
            position_ids = torch.arange(inputs_embeds.shape[1], device=inputs_embeds.device) + past_seen_tokens
            position_ids = position_ids.unsqueeze(0)

        causal_mask = create_causal_mask(
            config=self.config,
            inputs_embeds=inputs_embeds,
            attention_mask=attention_mask,
            past_key_values=past_key_values,
            position_ids=position_ids,
        )

        inputs_embeds = self.embed_dropout(inputs_embeds)
        hidden_states = inputs_embeds
        position_embeddings = self.rotary_emb(hidden_states, position_ids=position_ids)

        for decoder_layer in self.layers[: self.config.num_hidden_layers]:
            hidden_states = decoder_layer(
                hidden_states,
                attention_mask=causal_mask,
                position_ids=position_ids,
                past_key_values=past_key_values,
                use_cache=use_cache,
                position_embeddings=position_embeddings,
                **kwargs,
            )

        hidden_states = self.final_layernorm(hidden_states)

        return BaseModelOutputWithPast(
            last_hidden_state=hidden_states,
            past_key_values=past_key_values,
        )


@auto_docstring
class PhiForCausalLM(PhiPreTrainedModel, GenerationMixin):
    _tied_weights_keys = {"lm_head.weight": "model.embed_tokens.weight"}
    _tp_plan = {"lm_head": "colwise_gather_output"}
    _pp_plan = {"lm_head": (["hidden_states"], ["logits"])}

    def __init__(self, config):
        super().__init__(config)
        self.model = PhiModel(config)
        self.vocab_size = config.vocab_size
        self.lm_head = nn.Linear(config.hidden_size, config.vocab_size, bias=True)

        # Initialize weights and apply final processing
        self.post_init()

    @can_return_tuple
    @auto_docstring
    def forward(
        self,
        input_ids: torch.LongTensor | None = None,
        attention_mask: torch.Tensor | None = None,
        position_ids: torch.LongTensor | None = None,
        past_key_values: Cache | None = None,
        inputs_embeds: torch.FloatTensor | None = None,
        labels: torch.LongTensor | None = None,
        use_cache: bool | None = None,
        logits_to_keep: int | torch.Tensor = 0,
        **kwargs: Unpack[TransformersKwargs],
    ) -> CausalLMOutputWithPast:
        r"""
        Example:

        ```python
        >>> from transformers import AutoTokenizer, PhiForCausalLM

        >>> model = PhiForCausalLM.from_pretrained("meta-phi/Phi-2-7b-hf")
        >>> tokenizer = AutoTokenizer.from_pretrained("meta-phi/Phi-2-7b-hf")

        >>> prompt = "Hey, are you conscious? Can you talk to me?"
        >>> inputs = tokenizer(prompt, return_tensors="pt")

        >>> # Generate
        >>> generate_ids = model.generate(inputs.input_ids, max_length=30)
        >>> tokenizer.batch_decode(generate_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False)[0]
        "Hey, are you conscious? Can you talk to me?\nI'm not conscious, but I can talk to you."
        ```"""
        outputs: BaseModelOutputWithPast = self.model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_values=past_key_values,
            inputs_embeds=inputs_embeds,
            use_cache=use_cache,
            **kwargs,
        )

        hidden_states = outputs.last_hidden_state
        # Only compute necessary logits, and do not upcast them to float if we are not computing the loss
        slice_indices = slice(-logits_to_keep, None) if isinstance(logits_to_keep, int) else logits_to_keep
        logits = self.lm_head(hidden_states[:, slice_indices, :])

        loss = None
        if labels is not None:
            loss = self.loss_function(logits=logits, labels=labels, vocab_size=self.config.vocab_size, **kwargs)

        return CausalLMOutputWithPast(
            loss=loss,
            logits=logits,
            past_key_values=outputs.past_key_values,
            hidden_states=outputs.hidden_states,
            attentions=outputs.attentions,
        )


class PhiForSequenceClassification(GenericForSequenceClassification, PhiPreTrainedModel):
    pass


class PhiForTokenClassification(GenericForTokenClassification, PhiPreTrainedModel):
    pass


__all__ = [
    "PhiPreTrainedModel",
    "PhiModel",
    "PhiForCausalLM",
    "PhiForSequenceClassification",
    "PhiForTokenClassification",
]


def load_weight(model,name,layer_idx=0):
    print(f"Loading weights from Hugging Face: {name}...")
    
    # 下载模型（优先下载 safetensors）
    model_dir = snapshot_download(repo_id=name, allow_patterns=["*.safetensors", "*.bin", "*.json"])
    
    target_state_dict = model.state_dict()
    new_state_dict = {}
    
    # 查找权重文件
    weight_files = [f for f in os.listdir(model_dir) if f.endswith(('.safetensors', '.bin'))]
    
    for weight_file in weight_files:
        file_path = os.path.join(model_dir, weight_file)
        if weight_file.endswith('.safetensors'):
            shard_dict = load_file(file_path, device="cpu")
        else:
            shard_dict = torch.load(file_path, map_location="cpu", weights_only=True)
            
        for key, value in shard_dict.items():
            # 移除 'model.' 前缀以匹配 PhiModel 结构
            clean_key = key.replace("model.", "")
            
            # 1. 加载全局参数 (Embedding, Norm)
            if clean_key in target_state_dict and "layers" not in clean_key:
                new_state_dict[clean_key] = value
            
            # 2. 加载指定的 Transformer 层到本地的 layers.0
            elif f"layers.{layer_idx}." in clean_key:
                mapped_key = clean_key.replace(f"layers.{layer_idx}.", "layers.0.")
                if mapped_key in target_state_dict:
                    new_state_dict[mapped_key] = value
                    
        del shard_dict
    
    missing, unexpected = model.load_state_dict(new_state_dict, strict=False)
    print(f"Weights loaded. Missing: {len(missing)}, Unexpected: {len(unexpected)}")
    return model


def build_reduced_model(name):
    """一键构建函数"""
    config = PhiConfig()
    config.num_hidden_layers = 1
    # config.attn_implementation="eager"
    
    model = PhiModel(config)
    
    
    
    model = load_weight(model, name)

    model.eval()

    return model, config



def export_decoding_mlir(model, config, export_path, device="cpu"):
    # 确保模型在正确的设备和模式
    model = model.to(device).eval()
    
    # 关键点 1：定义符合原模型 forward 签名的 Wrapper
    class DecodingWrapper(torch.nn.Module):
        def __init__(self, m, cfg):
            super().__init__()
            self.m = m
            self.cfg = cfg
            self.max_seq_len = 1024 # 强制 context_length
            self.prefill_len = self.max_seq_len -1

            # Phi-1 参数：batch=1, heads, seq_len=1 (只存过去的), head_dim
            num_heads = cfg.num_attention_heads
            head_dim = cfg.hidden_size // num_heads
            
            # 初始化一个伪造的 past_key_value (假设过去已经处理了 0 个 token)
            # 形状: (batch, num_heads, past_seq_len, head_dim)
            self.register_buffer("past_k", torch.zeros(1, num_heads, self.prefill_len, head_dim))
            self.register_buffer("past_v", torch.zeros(1, num_heads, self.prefill_len, head_dim))
        class _SimpleCache:
            """
            轻量 Cache，提供 transformers PhiModel 期望的接口：
            - get_seq_length() -> int
            - get_mask_sizes(q_length, layer_idx) -> (kv_length, kv_offset)
            - update(key_states, value_states, layer_idx=None) -> (key_concat, value_concat)
            语义：
            - 过去长度 P = past_k.shape[2]
            - 当前 query 长度 q_length = key_states.shape[2]
            - 返回 kv_length = P + q_length, kv_offset = P
            """
            def __init__(self, past_k, past_v):
                # 保留引用（buffer）以便 update 时修改状态
                self.past_k = past_k
                self.past_v = past_v

            def get_seq_length(self):
                # 过去缓存的 token 数
                return int(self.past_k.shape[2])

            def get_mask_sizes(self, q_length: int, layer_idx: int | None = None):
                """
                返回 (kv_length, kv_offset)
                kv_length = past_seq_len + q_length
                kv_offset = past_seq_len (也就是当前 query 在整体 kv 上的起始偏移)
                """
                past_len = self.get_seq_length()
                kv_length = past_len + int(q_length)
                kv_offset = past_len
                return kv_length, kv_offset

            def update(self, key_states, value_states, layer_idx=None):
                """
                key_states/value_states: [batch, num_heads, seq_len, head_dim] (当前 step)
                将新的 key/value 拼接到 past 上，并返回拼接后的 (key, value)，即
                [batch, num_heads, past_seq_len + seq_len, head_dim]
                """
                # 确保 device/dtype 一致
                if self.past_k.device != key_states.device:
                    self.past_k = self.past_k.to(key_states.device)
                    self.past_v = self.past_v.to(value_states.device)

                # 拼接
                self.past_k = torch.cat((self.past_k, key_states), dim=2)
                self.past_v = torch.cat((self.past_v, value_states), dim=2)

                # 返回给调用方：作为“当前可用”的 key/value（被 attention 直接使用）
                return self.past_k, self.past_v
            
        def forward(self, input_ids):
            # # 注意：transformers 的 PhiModel 需要 past_key_values 或者是 Cache 对象
            # # 这里我们手动构造元组形式，这会被内部转换为缓存
            # past_key_values = ((self.past_k, self.past_v),)
            
            # # 这里的 position_ids 必须显式提供，否则导出时会自动生成arange导致形状不固定
            # position_ids = torch.tensor([[0]], dtype=torch.long, device=input_ids.device)
            
            # outputs = self.m(
            #     input_ids=input_ids,
            #     past_key_values=past_key_values,
            #     position_ids=position_ids,
            #     use_cache=True,
            #     return_dict=False # 导出时建议关闭 return_dict 以减少层级
            # )
            # 使用 SimpleCache 实例（而不是 tuple）
            past_cache = DecodingWrapper._SimpleCache(self.past_k, self.past_v)

            # position_ids 必须显式提供以锁定形状
            #position_ids = torch.tensor([[0]], dtype=torch.long, device=input_ids.device)
            position_ids = torch.tensor(
                            [[self.past_k.shape[2]]],
                        )
            outputs = self.m(
                input_ids=input_ids,
                past_key_values=past_cache,
                position_ids=position_ids,
                use_cache=True,
                return_dict=False
            )
            # outputs[0] 是 last_hidden_state
            return outputs[0]

    wrapper = DecodingWrapper(model,config)

    # 关键点 2：构造符合 Decoding 阶段形状的输入 (1, 1)
    # 假设我们只推理当前这一个 token
    decoding_input = torch.zeros((1, 1), dtype=torch.long, device=device) 

    # 关键点 3：预热 (Warm-up)
    # 这一步非常重要！因为原代码中 cache 开始是 None。
    # 如果不运行这一步，FX 追踪到的 cache 分支可能是无效的。
    with torch.no_grad():
        
        _ = wrapper(decoding_input)

    # 关键点 4：导出配置
    decomp_table = get_decomposition_table()

    print("Starting MLIR export for decoding step...")
    try:
        # 使用 fx.export_and_import
        mlir_module = fx.export_and_import(
            wrapper, 
            decoding_input, 
            # 如果你想支持动态长度，这里可以加 dynamic_shapes
            output_type="linalg-on-tensors", 
            strict=False,
            decomposition_table=decomp_table,
        )

        with open(export_path, "w") as f:
            f.write(str(mlir_module))
        print(f"Success! Decoding step MLIR saved to {export_path}")
        
    except Exception as e:
        print(f"Export failed! Error: {e}")
        print("\n提示：如果报错涉及 'torch.cat'，是因为 linalg 对动态增长的 Tensor 支持较难。")
        print("建议先尝试将 output_type 改为 'torch' 看看能否成功导出 Torch 方言的 MLIR。")
    
if __name__ == "__main__":
    #config = OPTConfig()
    ALL_ATTENTION_FUNCTIONS.get_interface = lambda impl, default: eager_attention_forward

    reduced_model, config= build_reduced_model("microsoft/phi-1")
    
    #export_to_pt(reduced_model, tokenizer, EXPORT_Prefill_PATH, device=DEVICE)
    EXPORT_Decode_PATH = "phi1Decoding_wogemv.mlir"
    export_decoding_mlir(reduced_model, config, EXPORT_Decode_PATH)